### ISSUE TITLE
compatibility with PS 6 core?

### ISSUE THREAD

**Issue by ghost** [datenteiler/SQLiteModule#1]
hi, it seems that all of the other sqlite modules have issues w/ powershell core. seeing that this seems to be newer code, and more recently updated than PSSQLite and SimplySql, which both have the same issues w/ core.

has this been tested for compatibility w/ linux/macos using powershell core?

**Comment by datenteiler** [comment]
Hi,

yes it's compatible to PS Core and tested on Linux and Windows with Core (I don't have a Mac). The module is also working on Arm e.g. on the Raspberry PI with Raspbian.

![SQLiteModule](https://user-images.githubusercontent.com/3180008/62314438-460d9c00-b493-11e9-9633-bd2845ffef56.png)
